language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-29
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-android-support # because I'm use support library
  - extra-android-m2repository # because I'm use support library
  - extra-android-m2repository
  - $ANDROID_TARGET
  - sys-img-x86-android-21
  #- sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  
 

  licenses:
    - '.+'
sudo: false

install: true

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi x86
  - emulator -avd test -memory 1500 -no-accel -gpu swiftshader -camera-back none -camera-front none -no-boot-anim -no-snapshot-save -no-snapstorage &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - chmod +x gradlew
  
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  
  #- emulator -avd test -no-skin -no-audio -no-window &
  
  - ./gradlew assembleRelease --stacktrace
  - ./gradlew lint test
  - ./gradlew connectedAndroidTest
  - ./gradlew connectedAndroidTest coveralls
 

