
CREATE TABLE STUDENTS(STUDENT_NO VARCHAR(20) PRIMARY KEY,
FNAME VARCHAR(20) NOT NULL, LNAME VARCHAR(20) NOT NULL,
PASSWORD TEXT NOT NULL,
EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE, CONTACT_NO VARCHAR(15) NOT NULL);

CREATE TABLE CREDIT(STUDENT_NO VARCHAR(20) PRIMARY KEY,
KUDU_BUCKS DECIMAL(6,2) NOT NULL,
FOREIGN KEY(STUDENT_NO) REFERENCES STUDENTS(STUDENT_NO));


CREATE TABLE MARKET(MARKET_ID INT AUTO_INCREMENT PRIMARY KEY,
CATEGORY VARCHAR(20) NOT NULL);

CREATE TABLE CLOTHES(CLOTHES_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL);

CREATE TABLE EVENTS(EVENTS_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL);

CREATE TABLE FOOD(FOOD_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL,
EXPIRY_DATE DATE NOT NULL);

CREATE TABLE STATIONARY(STATIONARY_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL);
