
CREATE TABLE STUDENTS(STUDENT_NO VARCHAR(20) PRIMARY KEY,
FNAME VARCHAR(20) NOT NULL, LNAME VARCHAR(20) NOT NULL,
PASSWORD TEXT NOT NULL,
EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE, CONTACT_NO VARCHAR(15) NOT NULL);

CREATE TABLE CREDIT(STUDENT_NO VARCHAR(20) PRIMARY KEY,
KUDU_BUCKS DECIMAL(6,2) NOT NULL,
FOREIGN KEY(STUDENT_NO) REFERENCES STUDENTS(STUDENT_NO));


CREATE TABLE MARKET(MARKET_ID INT AUTO_INCREMENT PRIMARY KEY,
CATEGORY VARCHAR(20) NOT NULL);

CREATE TABLE CLOTHES(CLOTHES_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL);

CREATE TABLE EVENTS(EVENTS_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL);

CREATE TABLE FOOD(FOOD_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL,
EXPIRY_DATE DATE NOT NULL);

CREATE TABLE STATIONARY(STATIONARY_ID INT AUTO_INCREMENT PRIMARY KEY,
MARKET_ID INT NOT NULL,
FOREIGN KEY(MARKET_ID) REFERENCES MARKET(MARKET_ID),
NAME VARCHAR(100) NOT NULL,PRICE DECIMAL(6,2) NOT NULL);

CREATE TABLE EVENT_RATINGS(EVENTS_ID INT NOT NULL, STUDENT_NO VARCHAR(20) NOT NULL, RATING
 DOUBLE, FOREIGN KEY(EVENTS_ID) REFERENCES EVENTS(EVENTS_ID), FOREIGN KEY(STUDENT_NO) REFERENCES
STUDENTS(STUDENT_NO), PRIMARY KEY(EVENTS_ID, STUDENT_NO));

 CREATE TABLE FOOD_RATINGS(FOOD_ID INT NOT NULL, STUDENT_NO VARCHAR(20) NOT NULL, RATING DOUBLE, FOREIGN KEY(FOOD_ID) REFERENCES FOOD(FOOD_ID), FOREIGN KEY(STUDENT_NO) REFERENCES STUDENTS(
STUDENT_NO), PRIMARY KEY(FOOD_ID, STUDENT_NO));

CREATE TABLE CLOTHES_RATINGS(CLOTHES_ID INT NOT NULL, STUDENT_NO VARCHAR(20) NOT NULL, RATING DOUBLE,
 FOREIGN KEY(CLOTHES_ID) REFERENCES CLOTHES(CLOTHES_ID),
 FOREIGN KEY(STUDENT_NO) REFERENCES STUDENTS(STUDENT_NO), PRIMARY KEY(CLOTHES_ID, STUDENT_NO));

CREATE TABLE STATIONARY_RATINGS(STATIONARY_ID INT NOT NULL, STUDENT_NO VARCHAR(20) NOT NULL,
 RATING DOUBLE, FOREIGN KEY(STATIONARY_ID) REFERENCES STATIONARY(STATIONARY_ID), 
FOREIGN KEY(STUDENT_NO) REFERENCES STUDENTS(STUDENT_NO), PRIMARY KEY(STATIONARY_ID, STUDENT_NO));